config/routes.rb
Rails.application.routes.draw do
  resources :courses
  devise_for :users
  root 'welcome#index'
  resources :students, only: [:index, :show]
  post 'enroll', to: 'course_users#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :course_users
    has_many :users, through: :course_users
end

app/models/course_user.rb
class CourseUser < ApplicationRecord
    belongs_to :user
    belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :course_users
  has_many :courses, through: :course_users
  
  def is_enrolled?(course)
    self.courses.where(id: course).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/course_users_controller.rb
class CourseUsersController < ApplicationController
    def create
        puts params[:course_id]
        course = Course.find(params[:course_id])
        puts course
        current_user.course_users.build(course_id: course.id)
        if current_user.save
            flash[:notice] = "Successfully enrolled to the course"
        else
            flash[:alert] = "Something went wrong"
        end
        
        redirect_to courses_path
        
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:code, :name, :description)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def index
        @students = User.all
    end
    
    def show
        @student = User.find(params[:id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit class: "waves-effect waves-default btn center" %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>


<div class="p-top">
    <%= link_to 'Show', @course %> |
    <%= link_to 'Back', courses_path %>
</div>

app/views/courses/index.html.erb
<h3 class="center-align">Course Listings</h3>

<% if current_user %>
  <%= link_to 'Create New Course', new_course_path, class: "btn" %>
<% end %>

<div class="row">
  <% @courses.each do |course| %>
    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text index-card-content">
          <span class="card-title"><%= course.code %> <br> <%= course.name %></span>
          <p><%= truncate(course.description, :length => 480) %></p>
        </div>
        <div class="card-action">
          <% if current_user && !current_user.is_enrolled?(course.id) %>
            <%= link_to "ENROLL", enroll_path(course_id: course.id), method: :post %>
          <% end %>
          <%= link_to "INFO", course %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<div class="p-top">
    <%= link_to 'Back', courses_path %>
</div>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col s12 m12">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title center-align"><%= @course.code %> <br> <%= @course.name %></span>
        <p><%= @course.description %></p>
      </div>
      <div class="card-action">
        <% if current_user %>
          <%= link_to "EDIT", edit_course_path(@course) %>
          <% if !current_user.is_enrolled?(@course.id) %>
            <%= link_to "ENROLL", enroll_path(course_id: @course.id), method: :post %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
            
<%= link_to 'Back', courses_path, class: "waves-effect waves-default btn" %>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Tech University</h5>
        <p class="grey-text text-lighten-4">The future of development training.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Information</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Contact</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2021 Tech University
    <a class="grey-text text-lighten-4 right" href="#!">About</a>
    </div>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% if notice %>
    <div id="notice" class="alert">
      <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
      <%= notice %>
    </div>
<% elsif alert %>
    <div id="notice" class="alert">
      <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
      <%= alert %>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav>
  <div class="nav-wrapper">
    <%= link_to "Tech University ", root_path, class: "brand-logo right" %>
    <ul id="nav-mobile" class="left hide-on-med-and-down">
      <li><%= link_to "Courses", courses_path %></li>
      <li><%= link_to "Students", students_path %></li>
      
      <% if current_user %>
        <li>
          <a class="dropdown-trigger" href="#!" data-target="dropdown1">
            <%= current_user.email %>
            <i class="material-icons right">arrow_drop_down</i>
          </a>
          <ul id="dropdown1" class="dropdown-content">
            <li><%= link_to "My Profile", student_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Sign in", user_session_path %></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UnivApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main>
      <div class="container">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/students/index.html.erb
<h3 class="center-align">Students Directory</h3>

<div class="row">
  <% @students.each do |student| %>
    <div class="col s12 m4">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
            <i class="large material-icons">account_box</i> 
            <span class="card-title">Email: <%= student.email %></span>
            <strong>Course Enrollments:</strong>
          
            <% if student.courses.exists? %>
                <% student.courses.each do |course| %>
                    <p><i class="tiny material-icons">keyboard_arrow_right</i> <%= course.name %></p>
                <% end %>
            <% else %>
                <p><i>No Course enrolled</i></p>
            <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/students/show.html.erb
<h3 class="center-align">My Profile</h3>

<div class="row">
  <div class="col s12 m4"></div>
  <div class="col s12 m4">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
          <i class="large material-icons">account_box</i> 
          <span class="card-title">Email: <%= @student.email %></span>
          <strong>Course Enrollments:</strong>
        
          <% if @student.courses.exists? %>
              <% @student.courses.each do |course| %>
                  <p><%= course.name %></p>
              <% end %>
          <% else %>
              <p><i>No Course enrolled</i></p>
          <% end %>
      </div>
    </div>
    
    <%= link_to 'Edit Profile', edit_user_registration_path(@student), class: "waves-effect waves-default btn" %>
    
  </div>
</div>

app/views/welcome/index.html.erb
<h2 class="center-align">Welcome to Tech University</h2>
<div class="center-align">
    <%= image_tag 'Professor-rafiki.png', size: "500" %>
</div>